MAINT-27699 : Auto activities of documents
exodev/ecms pull request #702
Opened 2020-09-09 15:58 UTC by Rdidmohamedelhadi

Hide activities (in comments forms when renaming, moving, or adding tags to a document)

2020-09-09 17:34 UTC, ahamdi requested changes
I think there is a misunderstanding with the requirement, we need to disable the generation of those comments when the Documents activities are disabled (check documentation here https://docs.exoplatform.org/en/6.0/Configuration.html?highlight=activity%20disable#enabling-disabling-any-activity-type ) and not to disable them completely.

2020-09-11 11:15 UTC, ahamdi submitted a review, later dismissed
LGTM
Please propose the needed content to add to the documentation of Activity types about the activity types events of rename document, move document etc ..

2020-09-11 11:39 UTC, mzorai commented
> LGTM
> Please propose the needed content to add to the documentation of Activity types about the activity types events of rename document, move document etc ..

@Rdidmohamedelhadi yep please add a task into the board with the needed details, thanks

2020-09-11 11:40 UTC, Rdidmohamedelhadi commented
> > LGTM
> > Please propose the needed content to add to the documentation of Activity types about the activity types events of rename document, move document etc ..
> 
> @Rdidmohamedelhadi yep please add a task into the board with the needed details, thanks

ok

2020-09-14 14:58 UTC, ahamdi commented on ecms-social-integration/src/main/java/org/exoplatform/wcm/ext/component/activity/listener/Utils.java
> +  private static final String RESOURCE_BUNDLE_KEY_EDIT_NAME   = "SocialIntegration.messages.editName";
```suggestion
  private static final String RESOURCE_BUNDLE_KEY_RENAME   = "SocialIntegration.messages.reame";
```

2020-09-14 15:00 UTC, ahamdi requested changes

2020-09-14 15:00 UTC, ahamdi commented on ecms-social-integration/src/main/java/org/exoplatform/wcm/ext/component/activity/listener/Utils.java
> +      if (RESOURCE_BUNDLE_KEY_EDIT_NAME.equals(activityMsgBundleKey) && ! activityManager.isActivityTypeEnabled(RENAME_COMMENT)) {
```suggestion
      if (RESOURCE_BUNDLE_KEY_FILE_RENAMED.equals(activityMsgBundleKey) && ! activityManager.isActivityTypeEnabled(RENAME_COMMENT)) {
```

2020-09-14 16:50 UTC, ahamdi approved these changes

2020-09-15 09:52 UTC, merged