Task-29069 : Display correct error message when a file is not more accessible - JCR part
exodev/ecms pull request #713
Opened 2020-10-07 12:25 UTC by rdenarie

This commit fixes UI problem when displaying a document which have a problem with his binary content :
- FileExplorer
- Rest Access
- Chat
- News
- Stream

2020-10-07 16:22 UTC, ahamdi requested changes

2020-10-07 16:22 UTC, ahamdi commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/dms-extension/dms/artifacts/templates/file/views/view1.gtmpl
> +              <h4><%=binaryNotAvailable%></h4>
IMO you can  use _ctx.appRes("File.view.label.binary-not-available") instead 
```suggestion
            } else {
%>
              <h4><%=_ctx.appRes("File.view.label.binary-not-available")%></h4>
```

2020-10-07 16:22 UTC, ahamdi commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/dms-extension/dms/artifacts/templates/file/views/admin_view.gtmpl
> +              <h4><%=binaryNotAvailable%></h4>
IMO you can use _ctx.appRes("File.view.label.binary-not-available") instead
```suggestion
%>
              <h4><%=binaryNotAvailable%></h4>
```

2020-10-07 18:12 UTC, rdenarie commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/dms-extension/dms/artifacts/templates/file/views/view1.gtmpl
> +              <h4><%=binaryNotAvailable%></h4>
No we cant, because when this file is used for preview in stream, the resourcebundle locale.ecm.views is not present.

2020-10-07 18:12 UTC, rdenarie commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/dms-extension/dms/artifacts/templates/file/views/admin_view.gtmpl
> +              <h4><%=binaryNotAvailable%></h4>
No we cant, because when this file is used for preview in stream, the resourcebundle locale.ecm.views is not present.

2020-10-08 08:44 UTC, ahamdi approved these changes

2020-10-08 09:35 UTC, merged