Add Cloud Drives permissions page
exodev/ecms pull request #727
Opened 2020-11-02 09:37 UTC by AzmiTouil

2020-11-05 14:22 UTC, azayati requested changes
See review

2020-11-05 14:22 UTC, azayati commented on ecm-wcm-extension/src/main/webapp/attachments-selector/attachmentsService.js
> +  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/is-cloud-enabled`,{
```suggestion
  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/status`,{
```

2020-11-05 14:22 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/vue-app/cloudDriveService.js
> +  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/is-cloud-enabled`,{
```suggestion
  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/status`,{
```

2020-11-05 14:22 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/vue-app/cloudStorage/components/CloudStorage.vue
> +          method: "POST",
```suggestion
          method: "PATCH",
```

2020-11-05 14:22 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/vue-app/cloudStorage/components/CloudStorage.vue
> +        fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/cloud-Status`, {
```suggestion
        fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/status`, {
```

2020-11-05 14:22 UTC, azayati commented on core/connector/src/main/java/org/exoplatform/ecm/connector/clouddrives/FeaturesService.java
> +  @POST
```suggestion
  @PATCH
```

2020-11-05 17:40 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/resources/locale/navigation/group/platform/administrators_en.properties
> +cloudDrive.storage.page=Cloud Storage
Done !

2020-11-05 17:40 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/conf/clouddrive/portal/group/platform/administrators/pages.xml
> +        <application-ref>cloud-storage</application-ref>
Done !

2020-11-05 17:40 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/conf/clouddrive/portal/group/platform/administrators/pages.xml
> +    <access-permissions>manager:/platform/administrators</access-permissions>
Updated !

2020-11-05 17:40 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +      <path>/js/clouddrives-storage.bundle.js</path>
Done !

2020-11-05 17:40 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/portlet.xml
> +      <value>/cloud-storage.jsp</value>
Done !

2020-11-05 17:40 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/portlet.xml
> +      <short-title>Cloud Drive Admin</short-title>
Done !

2020-11-05 17:41 UTC, AzmiTouil commented on core/connector/src/main/java/org/exoplatform/ecm/connector/clouddrives/FeaturesService.java
> +  @Path("/is-cloud-enabled/")
Done !

2020-11-05 17:41 UTC, AzmiTouil commented on ecm-wcm-extension/src/main/webapp/attachments-selector/attachmentsService.js
> +  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/is-cloud-enabled`,{
Done !

2020-11-05 17:41 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/vue-app/cloudDriveService.js
> +  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/is-cloud-enabled`,{
Done !

2020-11-05 17:41 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/vue-app/cloudStorage/components/CloudStorage.vue
> +          method: "POST",
Done !

2020-11-05 17:41 UTC, AzmiTouil commented on apps/portlet-clouddrives/src/main/webapp/vue-app/cloudStorage/components/CloudStorage.vue
> +        fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/clouddrive/features/cloud-Status`, {
Done !

2020-11-05 17:41 UTC, AzmiTouil commented on core/connector/src/main/java/org/exoplatform/ecm/connector/clouddrives/FeaturesService.java
> +  @POST
Done !

2020-11-06 10:14 UTC, azayati requested changes
see review

2020-11-06 10:14 UTC, azayati commented on core/connector/src/main/java/org/exoplatform/ecm/connector/clouddrives/FeaturesService.java
> +   * Checks if is cloud drive enabled.
```suggestion
   * Checks if cloud drive is enabled.
```

2020-11-06 10:14 UTC, azayati commented on core/connector/src/main/java/org/exoplatform/ecm/connector/clouddrives/FeaturesService.java
> +   * Update cloud Drive permissions.
```suggestion
   * Set cloud Drive permissions.
```

2020-11-06 10:14 UTC, azayati commented on core/connector/src/main/java/org/exoplatform/ecm/connector/clouddrives/FeaturesService.java
> +  public Response changeCloudDriveStatus(@Context UriInfo uriInfo) {
```suggestion
  public Response setCloudDriveStatus(@Context UriInfo uriInfo) {
```

2020-11-06 13:52 UTC, azayati approved these changes
LGTM

2020-11-06 14:21 UTC, merged