MAINT-25904 : Fix display name of document
exodev/ecms pull request #732
Opened 2020-11-06 16:00 UTC by Rdidmohamedelhadi

2020-11-06 17:39 UTC, ahamdi requested changes

2020-11-06 17:39 UTC, ahamdi commented on apps/portlet-explorer/src/main/webapp/javascript/eXo/ecm/MultiUpload.js
> +		fileName = decodeURI(fileName);
No need for this, just decodeURIComponent twice on the filename

2020-11-09 09:19 UTC, Rdidmohamedelhadi commented on apps/portlet-explorer/src/main/webapp/javascript/eXo/ecm/MultiUpload.js
> +		fileName = decodeURI(fileName);
ok

2020-11-09 09:26 UTC, ahamdi commented
Could you rebase it on feature/maintenance ?

2020-11-09 09:30 UTC, Rdidmohamedelhadi commented
> Could you rebase it on feature/maintenance ?

done !

2020-11-09 10:46 UTC, ahamdi approved these changes

2020-11-09 11:44 UTC, merged