MAINT-36592 : Name of document containing % not ok in copy’s pop up
exodev/ecms pull request #742
Opened 2020-11-16 13:34 UTC by Rdidmohamedelhadi

2020-11-19 11:54 UTC, ahamdi reviewed
Coudl you rebase the branch ?

2020-11-19 12:52 UTC, Rdidmohamedelhadi commented
> Coudl you rebase the branch ?

done !

2020-11-19 14:31 UTC, ahamdi requested changes

2020-11-19 14:31 UTC, ahamdi commented on apps/portlet-explorer/src/main/webapp/groovy/webui/component/explorer/versions/UIDocumentAutoVersionForm.gtmpl
> +    String msg = URLDecoder.decode(msgArguments[i], "UTF-8");
Please check the nullity and the emptiness of the parameter. Then do a try/catch to avoid issues if the document title is not encoded.

2020-11-19 15:03 UTC, Rdidmohamedelhadi commented on apps/portlet-explorer/src/main/webapp/groovy/webui/component/explorer/versions/UIDocumentAutoVersionForm.gtmpl
> +    String msg = URLDecoder.decode(msgArguments[i], "UTF-8");
ok

2020-11-20 13:57 UTC, ahamdi commented on apps/portlet-explorer/src/main/webapp/groovy/webui/component/explorer/versions/UIDocumentAutoVersionForm.gtmpl
> +      }
```suggestion
      def msg = msgArguments[i];
      try{
        String msg = URLDecoder.decode(URLDecoder.decode(msg, "UTF-8"), "UTF-8");
      }cache(Exception e){
        // Nothing to do
      }
```

2020-11-20 16:04 UTC, Rdidmohamedelhadi commented on apps/portlet-explorer/src/main/webapp/groovy/webui/component/explorer/versions/UIDocumentAutoVersionForm.gtmpl
> +      }
Done !

2020-11-20 16:21 UTC, ahamdi approved these changes

2020-11-21 19:55 UTC, merged