MAINT-35382: Make sure to display correct file name after download from webdav.
exodev/ecms pull request #751
Opened 2020-12-01 09:33 UTC by mdiha

2020-12-04 17:33 UTC, ahamdi requested changes

2020-12-04 17:33 UTC, ahamdi commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +      if (StringUtils.equals(response.getMetadata().get("content-type").get(0).toString(), "application/octet-stream")) {
Why did you add this check ? is it to find whether it is a file or a folder ?

2020-12-07 07:46 UTC, mdiha commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +      if (StringUtils.equals(response.getMetadata().get("content-type").get(0).toString(), "application/octet-stream")) {
Yes since for the folder we need to display the node title.

2020-12-07 07:56 UTC, mdiha commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +      if (StringUtils.equals(response.getMetadata().get("content-type").get(0).toString(), "application/octet-stream")) {
Yes to check if it is a file.

2020-12-07 17:26 UTC, ahamdi commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +      if (StringUtils.equals(response.getMetadata().get("content-type").get(0).toString(), "application/octet-stream")) {
Could you use the JCP APUI to do that ? all files are of type nt:file
You need just to do : 
```
// Check if the content is a file
node.isNodeType("nt:file");
```

2020-12-08 13:04 UTC, mdiha commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +      if (StringUtils.equals(response.getMetadata().get("content-type").get(0).toString(), "application/octet-stream")) {
Done

2020-12-08 13:32 UTC, ahamdi commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +  private String getFileName(String repoPath) {
No need to recalculate the node as you got it already in the top function

2020-12-08 17:09 UTC, mdiha commented on core/services/src/main/java/org/exoplatform/services/cms/webdav/WebDavServiceImpl.java
> +  private String getFileName(String repoPath) {
Okay

2020-12-08 17:15 UTC, ahamdi approved these changes
LGTM

2020-12-09 08:41 UTC, merged